In [1]:
import numpy as np
import pandas as pd

n_data = 1000

# Menghasilkan data
usia = np.random.randint(18, 61, size=n_data)
gender = np.random.randint(0, 2, size=n_data)  # 0: Perempuan, 1: Laki-laki
gaji = np.random.randint(3000, 15000, size=n_data)
tingkat_pendidikan = np.random.choice(['SMA', 'D3', 'S1', 'S2'], size=n_data)
# Perbaikan: menghitung pengalaman kerja secara valid berdasarkan usia
tahun_pengalaman = np.array([np.random.randint(0, u - 17 + 1) for u in usia])
skor_kinerja = np.random.randint(0, 101, size=n_data)
departemen = np.random.choice(['IT', 'HR', 'Finance', 'Marketing', 'Production'], size=n_data)
kota = np.random.choice(['Bogor', 'Bandung', 'Sukabumi', 'Karawang', 'Bekasi'], size=n_data)
produktivitas = np.clip(np.random.normal(75, 10, size=n_data), 0, 100).round(2)

# Buat DataFrame
df = pd.DataFrame({
    'Usia': usia,
    'Gender': gender,
    'Gaji': gaji,
    'Tingkat Pendidikan': tingkat_pendidikan,
    'Pengalaman Kerja': tahun_pengalaman,
    'Skor Kinerja': skor_kinerja,
    'Departemen': departemen,
    'Kota': kota,
    'Produktivitas': produktivitas
})

# Mengubah label gender ke string
df['Gender'] = df['Gender'].map({0: 'Perempuan', 1: 'Laki-laki'})

# Menampilkan informasi data
print("\n=== Informasi Data ===")
print(df.info())

print("\n=== Lima Baris Pertama ===")
print(df.head())

# Analisis data
print("\n=== Distribusi Gender ===")
print(df['Gender'].value_counts())

print("\n=== Distribusi Tingkat Pendidikan ===")
print(df['Tingkat Pendidikan'].value_counts())

print("\n=== Distribusi Departemen ===")
print(df['Departemen'].value_counts())

print("\n=== Distribusi Kota ===")
print(df['Kota'].value_counts())

print("\n=== Rata-rata Produktivitas per Departemen ===")
print(df.groupby('Departemen')['Produktivitas'].mean().round(2))

print("\n=== Rata-rata Gaji berdasarkan Tingkat Pendidikan ===")
print(df.groupby('Tingkat Pendidikan')['Gaji'].mean().round(2))

print("\n=== Rata-rata Produktivitas berdasarkan Gender ===")
print(df.groupby('Gender')['Produktivitas'].mean().round(2))

# Simpan ke file CSV
df.to_csv('dataKaryawan.csv', index=False)

=== Informasi Data ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Usia                1000 non-null   int32
 1   Gender              1000 non-null   object
 2   Gaji                1000 non-null   int32
 3   Tingkat Pendidikan  1000 non-null   object
 4   Pengalaman Kerja    1000 non-null   int32
 5   Skor Kinerja        1000 non-null   int32
 6   Departemen          1000 non-null   object
 7   Kota                1000 non-null   object
 8   Produktivitas       1000 non-null   float64
dtypes: float64(1), int32(4), object(4)
memory usage: 54.8+ KB
None

=== Lima Baris Pertama ===
   Usia     Gender   Gaji Tingkat Pendidikan  Pengalaman Kerja  Skor Kinerja  \
0    48  Perempuan   3097                 S2                18            25
1    28  Laki-laki  11429                 S1                11            20
2    31  Perempuan   8866                 S1                 6            41
3    43  Perempuan   4751                 D3                14            58
4    24  Perempuan   9795                 S1                 6            75

   Departemen      Kota  Produktivitas
0   Marketing  Sukabumi          73.79
1  Production     Bogor          75.73
2     Finance     Bogor          81.07
3  Production  Karawang          66.20
4          IT   Bandung          72.73

=== Distribusi Gender ===
Gender
Perempuan    508
Laki-laki    492
Name: count, dtype: int64

=== Distribusi Tingkat Pendidikan ===
Tingkat Pendidikan
S2     260
SMA    255
D3     248
S1     237
Name: count, dtype: int64

=== Distribusi Departemen ===
Departemen
IT            211
Finance       206
HR            197
Production    196
Marketing     190
Name: count, dtype: int64

=== Distribusi Kota ===
Kota
Sukabumi    210
Bogor       208
Karawang    203
Bekasi      203
Bandung     176
Name: count, dtype: int64

=== Rata-rata Produktivitas per Departemen ===
Departemen
Finance       75.54
HR            76.54
IT            74.60
Marketing     75.87
Production    76.16
Name: Produktivitas, dtype: float64

=== Rata-rata Gaji berdasarkan Tingkat Pendidikan ===
Tingkat Pendidikan
D3     9013.45
S1     9102.89
S2     8925.60
SMA    9257.61
Name: Gaji, dtype: float64

=== Rata-rata Produktivitas berdasarkan Gender ===
Gender
Laki-laki    75.58
Perempuan    75.85
Name: Produktivitas, dtype: float64